name: STM32 Full Build CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Install dependencies
      - name: Install toolchain & tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-arm-none-eabi \
            make \
            python3 \
            srecord \
            cppcheck

      # 3. Make scripts executable
      - name: Make scripts executable
        run: find . -name "*.sh" -exec chmod +x {} \;

      # 4. Run your build
      - name: Run full build
        run: ./combined_image/FULL_IMAGE.sh

      - name: Upload BM artifact
        uses: actions/upload-artifact@v4
        with:
          name: BM
          path: BM/Tools/*.elf

      - name: Upload BTLD artifact
        uses: actions/upload-artifact@v4
        with:
          name: BTLD
          path: BTLD/Tools/*.elf

      - name: Upload Application artifact
        uses: actions/upload-artifact@v4
        with:
          name: Application
          path: APP/Tools/*.elf

      # 5. Upload final hex
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: full-image
          path: combined_image/full_image.hex
      - name: Firmware size
        run: arm-none-eabi-size BM/Tools/*.elf BTLD/Tools/*.elf Application/Tools/*.elf      
  Static_Analysis:
      - name: Run cppcheck
        run: cppcheck --enable=all --inconclusive --force .    